site_name: "Notes :: Xecades"
theme:
  name: material
  language: en
  custom_dir: overrides
  icon:
    logo: material/xml
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - navigation.top
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: "PT Serif"
    code: "JetBrains Mono"

extra_css:
  - assets/css/extra.css

plugins:
  - search
