site_name: "Notes :: Xecades"
theme:
  name: material
  language: en
  custom_dir: overrides
  icon:
    logo: material/xml
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - navigation.top
    - search.suggest
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: fontawesome/solid/sun
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: fontawesome/solid/moon
        name: Switch to dark mode
  font:
    text: "PT Serif"
    code: "JetBrains Mono"

extra_css:
  - assets/css/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - index.md
  - Computer Science:
    - C / C++:
      - Cheatsheet: cs/c-cpp/c-language-cheatsheet.md
  - Math:
    - Mathematical Analysis:
      - Completeness Of Real Numbers: math/ma/completeness-of-real-numbers.md
  - Others:
    - macOS Command Collection: others/macOS-command-collection.md
