site_name: "Notes :: Xecades"
theme:
  name: material
  language: en
  custom_dir: overrides
  icon:
    logo: material/xml
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - navigation.top
    - search.suggest
    - content.code.copy
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/lightbulb-off
        name: Switch to dark mode
  font:
    text: "PT Serif"
    code: "JetBrains Mono"

extra_css:
  - assets/css/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

repo_url: https://github.com/Xecades/Notes
repo_name: Xecades/Notes

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2023 Xecades

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Xecades
    - icon: fontawesome/solid/envelope
      link: "mailto:i@xecades.xyz"
    - icon: fontawesome/brands/telegram
      link: https://t.me/Xecades
  analytics:
    provider: google
    property: G-SZXL7N0Q4X

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - index.md
  - Computer Science:
    - C / C++:
      - Cheatsheet: cs/c-cpp/c-language-cheatsheet.md
  - Math:
    - Mathematical Analysis:
      - Completeness Of Real Numbers: math/ma/completeness-of-real-numbers.md
  - Others:
    - macOS Command Collection: others/macOS-command-collection.md
