import { library } from "@fortawesome/fontawesome-svg-core";
import {
    faAngleDown,
    faAngleRight,
    faArrowUpRightFromSquare,
    faAsterisk,
    faAtom,
    faBars,
    faBoxArchive,
    faCaretLeft,
    faCaretRight,
    faChevronLeft,
    faCode,
    faCube,
    faExclamationCircle,
    faExclamationTriangle,
    faEye,
    faFaceFrown,
    faFile,
    faFlag,
    faFolder,
    faInfoCircle,
    faLightbulb,
    faLink,
    faMagnifyingGlass,
    faSpinner,
    faXmark,
} from "@fortawesome/free-solid-svg-icons";
import { faStar } from "@fortawesome/free-regular-svg-icons";
import { faGithub } from "@fortawesome/free-brands-svg-icons";

library.add(
    faAngleRight,
    faAngleDown,
    faBars,
    faMagnifyingGlass,
    faCaretRight,
    faCaretLeft,
    faXmark,
    faFile,
    faFolder,
    faFaceFrown,
    faAsterisk,
    faCube,
    faLightbulb,
    faInfoCircle,
    faExclamationCircle,
    faExclamationTriangle,
    faLink,
    faArrowUpRightFromSquare,
    faStar,
    faGithub,
    faSpinner,
    faChevronLeft,
    faCode,
    faAtom,
    faBoxArchive,
    faFlag,
    faEye
);
