name: Build and Deploy to Vercel

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout App Repository
              uses: actions/checkout@v3
              with:
                  path: app
                  fetch-depth: 0

            - name: Checkout Plugin Repository
              uses: actions/checkout@v3
              with:
                  repository: "Xecades/vite-plugin-vue-xecades-note"
                  path: plugin
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install Dependencies in app and plugin
              run: npm --prefix ./app ci && npm --prefix ./plugin ci

            - name: Build Plugin
              run: npm --prefix ./plugin run build

            - name: Link Plugin
              run: npm --prefix ./plugin link && npm --prefix ./app link vite-plugin-vue-xecades-note

            - name: Generate Cache
              run: npm --prefix ./app run cache

            - name: Build Project
              run: npm --prefix ./app run build

            - name: Deploy to Vercel
              uses: amondnet/vercel-action@v25
              with:
                  vercel-token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
                  vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
                  working-directory: ./app
                  vercel-args: "--prod"
